# Site settings
baseURL = "https://killthead.com"
languageCode = "en-US"
title = "Kill The ad"
theme = "hugo-lens-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]
copyright = "&copy; Kill the ad."

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]

  # Header
  [params.header]
    title = "Kill The ad"
    description = "The butcher in cinematography"

  # Social Icons

  [[params.social]]
    label = "Instagram"
    icon = "fa-instagram"
    url = "https://www.instagram.com/killthead/"

    [[params.social]]
    label = "Email"
    icon = "fa-envelope-o"
    url = "mailto:for.rent.inpreferenceto.for.sale@gmail.com"

    [[params.social]]
    label = "Youtube"
    icon = "fa-youtube"
    url = "https://www.youtube.com/channel/UCbd37z7LQwWZT52suXMdypw/featured"



  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://html5up.net/license
